apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a4m09grox-nodejs 
  janus-idp.io/tekton: a4m09grox-nodejs
  backstage.io/kubernetes-id: a4m09grox-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a4m09grox-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  