apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a4m09grox-nodejs
  janus-idp.io/tekton: a4m09grox-nodejs
  backstage.io/kubernetes-id: a4m09grox-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a4m09grox-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
